version: "3.9"
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports: ["1883:1883"]
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  plantpot-backend:
    build: ./backend  
    container_name: plantpot-backend
    depends_on: [mosquitto]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/app/data/plantpotdb;AUTO_SERVER=TRUE
      - MQTT_BROKER=tcp://mosquitto:1883
    ports: ["8080:8080"]
    volumes:
      - ./backend/data:/app/data

  plantpot-frontend:
    build: ./frontend
    container_name: plantpot-frontend
    ports: ["3000:80"]
    depends_on:
      - plantpot-backend