version: "3.9"
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports: ["1883:1883"]
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  plantpot-backend:
    build: ./backend  
    container_name: plantpot-backend
    depends_on: [mosquitto]
    environment:
      - MQTT_BROKER=tcp://mosquitto:1883
      - MQTT_CLIENT_ID=plantpot-listener
      - MQTT_TOPIC=sensors/esp32_1/soil
    ports: ["8080:8080"]
    volumes:
      - ./backend/data:/app/data